//LOCAL
//All contacts
GET http://localhost:3000/contacts

//Beatrice's info:
GET http://localhost:3000/contacts/62a2574b025249739a89b296
 
//Kiev's info:
GET http://localhost:3000/contacts/62a257df025249739a89b297

//Keikei's info:
GET http://localhost:3000/contacts/62a25814025249739a89b298

//POST (create new contact)
POST http://localhost:3000/contacts http/1.1 content-type: application/json

{
  "firstName":"Gwen", "lastName":"Gorrez", 
  "email":"gwen@mail.com", 
  "favoriteColor":"pink", 
  "birthday":"07/26/82"
}

//PUT (update) change first name
PUT http://localhost:3000/contacts/62a25814025249739a89b298 http/1.1 content-type: application/json
  {
    "firstName": "Karen Mhyrr",
    "lastName": "Alido",
    "email": "keikei@mail.com",
    "favoriteColor": "pink",
    "birthday": "04/30/01"
  }

//DELETE 
DELETE http://localhost:3000/contacts/62a8f6bbb03dac5df09ef8c7 http/1.1


//HEROKU
//All contacts
GET https://polar-spire-69659.herokuapp.com/contacts

//Beatrice's info:
GET https://polar-spire-69659.herokuapp.com/contacts/62a2574b025249739a89b296

//Kiev's info:
GET https://polar-spire-69659.herokuapp.com/contacts/62a257df025249739a89b297

//Keikei's info:
GET https://polar-spire-69659.herokuapp.com/contacts/62a25814025249739a89b298

//POST
POST https://polar-spire-69659.herokuapp.com/contacts http/1.1 content-type: application/json
{
  "firstName":"Mika", 
  "lastName":"Yamashita", 
  "email":"mika@mail.com", 
  "favoriteColor":"red", 
  "birthday":"04/18/98"
}

//PUT change fave color
PUT https://polar-spire-69659.herokuapp.com/contacts/62a8f707b03dac5df09ef8c8 http/1.1 content-type: application/json
{
  "firstName": "Delete",
  "lastName": "Me",
  "email": "delete@mail.com",
  "favoriteColor": "blue",
  "birthday": "08/08/08"
}

//DELETE
DELETE https://polar-spire-69659.herokuapp.com/contacts/62a8f707b03dac5df09ef8c8 http/1.1




